### Ansible is not responsible for generating account keys
# - name: Generate ssh keys
#   connection: local
#   hosts: localhost
#   gather_facts: false
#   roles:
#     - ssh_users_keygen

- name: Create ssh accounts
  hosts: ssh
  gather_facts: false
  roles:
    - ssh_users_create
