ssh:
  children:
    docker:

docker:
  children:
    docker_managers:
    docker_workers:

docker_managers:
  hosts:
    DOCK-MAN-00[1:3]:

docker_workers:
  hosts:
    DOCK-WOR-00[1:3]:
