all:
  children:
    local:
      hosts:
        localhost:
          ansible_connection: local

ssh:
  children:
    managers:
    workers:

docker:
  children:
    docker_managers:
    docker_workers:

docker_managers:
  children:
    managers:

docker_workers:
  children:
    workers:

managers:
  hosts:
    MANAGER00[1:3]:

workers:
  hosts:
    WORKER00[1:3]:
