key_private_name: docker_lab
key_type: ed25519
ssh_users_to_create:
  - user: deployer
    key_dir: "~/.ansible_keys"
    key_name: "docker_lab_deployer"
    key_type: "ed25519"
  - user: tristiisch
    key_dir: "~/.ansible_keys"
    key_name: "docker_lab_tristiisch"
    key_type: "ed25519"
