- name: Get worker token
  ansible.builtin.set_fact:
    manager_info: >
      {{
        groups['docker_managers'] | map('extract', hostvars) | selectattr('worker_token', 'defined') | first
      }}
  when: in_cluster == false

- name: Leave previous cluster
  docker_swarm:
    state: absent
    force: "{{ is_manager }}"
  when: is_stuck == true

- name: Join worker to the swarm
  docker_swarm:
    join_token: "{{ manager_info.worker_token }}"
    remote_addrs: ["{{ manager_info.ansible_default_ipv4.address }}:2377"]
    advertise_addr: "{{ ansible_default_ipv4.address }}:4567"
    state: join
  register: manager_join_result
  when: in_cluster == false
