- name: Add errors locations
  template:
    src: "locations.conf.j2"
    dest: "{{ nginx_config_dir }}/locations.conf"
  notify: reload_nginx

- name: Create directory for errors files
  file:
    path: "{{ nginx_errors_path }}"
    state: directory
    recurse: true
    owner: "{{ nginx_admin_user }}"
    group: "{{ nginx_process_group}}"
    mode: 0650
  notify: reload_nginx

- name: Copy errors files to destination directory
  copy:
    # src: "errors/{{ item }}"
    src: "errors/"
    dest: "{{ nginx_errors_path }}/"
    owner: "{{ nginx_admin_user }}"
    group: "{{ nginx_process_group}}"
    mode: 0650
  # with_items:
  #   - "*.html"
  #   - "*.css"
