- name: Delete default vhost
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - "{{ nginx_sites_enabled }}/default"
    - "{{ nginx_sites_available }}/default"
  notify: reload_nginx

- name: Add custom vhost
  template:
    src: "default.conf.j2"
    dest: "{{ nginx_sites_available }}/default.conf"
  notify: reload_nginx

- name: Create custom vhost files directory
  file:
    path: "{{ nginx_default_root }}"
    state: directory
    recurse: true
    owner: "{{ nginx_admin_user }}"
    group: "{{ nginx_process_group}}"
    mode: 0650
  notify: reload_nginx

- name: Copy custom vhost files
  template:
    src: "index.html.j2"
    dest: "{{ nginx_default_root }}/index.html"
    owner: "{{ nginx_admin_user }}"
    group: "{{ nginx_process_group}}"
    mode: 0650
  notify: reload_nginx

- name: Enable custom vhost
  file:
    src: "{{ nginx_sites_available }}/default.conf"
    dest: "{{ nginx_sites_enabled }}/default.conf"
    state: link
  notify: reload_nginx
