- name: Generate ssh key
  connection: local
  hosts: localhost
  gather_facts: no
  roles:
  - ssh_keygen

- name: Deploy ssh key
  hosts: ssh_account
  gather_facts: no
  roles:
  - ssh_user_create

- name: Test ssh connection
  hosts: ssh_account
  gather_facts: no
  roles:
  - ssh_user_test
