# - name: Remove ssh key on user Ansible
#   hosts: ssh
#   gather_facts: no
#   roles:
#   - ssh_user_remove_key

- name: Delete users
  hosts: ssh
  gather_facts: no
  roles:
  - ssh_users_delete
