# ansible_user: ansible
# ansible_ssh_private_key_file: ~/.ansible_keys/docker_lab
ssh_user_to_remove_key: ansible
ssh_user_to_remove_password: president
sudoers_group: adm
shell_default: /bin/bash
ssh_users_to_create:
  - user: president
    password: "$6$rounds=100000$JCiJe9SqVoi9klVz$FDq6bZcnW9qPzMdaj.Rh.I.kEu1134SMD5opRNFurWwJZgwZe48x3xitZym5l3W3AuS7.H/WOJkJq90bU/JuG1"
    comment: Default account
    groups:
      - adm
    sudoers: false
  - user: deployer
    password: "*"
    comment: Used to deploy applications
    groups:
      - docker
    sudoers: false
    key_dir: ~/.ansible_keys
    key_name: docker_lab_deployer
    key_type: ed25519
