- name: Install NGinX
  package:
    name: nginx
    state: present

- name: Install Python Lib for detecting packages versions
  package:
    name: python3-rpm
    state: present
  when: ansible_os_family == 'Suse'

- name: Gather facts about installed packages
  ansible.builtin.package_facts:
    manager: auto

- name: Print version of NGinX package
  debug:
    msg: "{{ ansible_facts.packages['nginx'][0]['version'] }}"

# - name: Install NGinX Extras
#   package:
#     name: nginx-extras
#     state: present

- name: Enable NGinX to start at boot
  service:
    name: nginx
    enabled: yes

- name: Ensure NGinX is running
  service:
    name: nginx
    state: started
