- name: reload_nginx
  service:
    name: nginx
    state: reloaded

# - name: Get latest logs for nginx service
#   systemd:
#     name: nginx
#     state: get_logs
#     lines: 10
#   register: nginx_logs

# - name: Print nginx logs
#   debug:
#     msg: "{{ nginx_logs.stdout_lines }}"
#   when: nginx_logs.stdout_lines is defined
