
- name: Create folder for ssh keys
  file:
    path: "{{ key_dir }}"
    state: directory
    mode: '0700'

- name: Generate ssh key
  openssh_keypair:
    path:  "{{ key_dir }}/{{ key_private_name }}"
    type: "{{ key_type }}"
    state: present
    force: no
