- name: Install NFS client packages
  ansible.builtin.package:
    name: nfs-common
    state: present
  become: true

- name: Ensure local mount directories exist
  ansible.builtin.file:
    path: "{{ item.local_path }}"
    state: directory
    mode: "{{ item.mode | default('0755') }}"
  loop: "{{ nfs_mounts }}"
  become: true

- name: Mount NFS shares
  ansible.builtin.mount:
    path: "{{ item.local_path }}"
    src: "{{ item.server }}:{{ item.remote_path }}"
    fstype: "{{ item.type }}"
    opts: "{{ item.options }}"
    state: mounted
  loop: "{{ nfs_mounts }}"
  become: true

- name: Ensure NFS mounts are persistent in fstab
  ansible.builtin.mount:
    path: "{{ item.local_path }}"
    src: "{{ item.server }}:{{ item.remote_path }}"
    fstype: "{{ item.type }}"
    opts: "{{ item.options }}"
    state: present
  loop: "{{ nfs_mounts }}"
  become: true
