- name: Get docker info
  docker_host_info:
  register: swarm_status

- name: Print cluster error if any
  fail:
    msg: "{{ swarm_status.host_info.Swarm.Error }}"
  when: swarm_status.host_info.Swarm.Error != ''
  ignore_errors: true

- name: Set fact if the node is in the swarm
  ansible.builtin.set_fact:
    in_cluster: >-
      {{
        swarm_status.host_info.Swarm.LocalNodeState == 'active'
        or swarm_status.host_info.Swarm.LocalNodeState == 'locked'
      }}
    is_stuck: >-
      {{
        swarm_status.host_info.Swarm.LocalNodeState == 'pending'
        or swarm_status.host_info.Swarm.LocalNodeState == 'error'
      }}
    is_inactive: "{{ swarm_status.host_info.Swarm.LocalNodeState == 'inactive' }}"

- name: Set fact if the node is a manager
  ansible.builtin.set_fact:
    is_manager: "{{ swarm_status.host_info.Swarm.ControlAvailable == true }}"

- name: Retrive cluster state
  ansible.builtin.set_fact:
    cluster_exists: >-
      {{
        groups['docker_managers']
        | map('extract', hostvars, 'is_manager')
        | select('defined')
        | list
        | length > 0
      }}
    cluster_healthy: >-
      {{
        groups['docker_managers']
        | map('extract', hostvars, 'in_cluster')
        | select('defined')
        | select('equalto', true)
        | list | length > 0
      }}
