- name: Create user {{ user_to_create }} using {{ ansible_user }}
  ansible.builtin.user:
    name: "{{ user_to_create }}"
    comment: "ansible node use this account using ssh"
    # Use '*' to disable password-based authentication while keeping the account active
    password: "*"
    # password_lock: true
    # password: "{{ 'P@ssword!' | password_hash('sha512') }}"
    # umask: 007
  register: user_created
  become: true

- name: Define permission on {{ user_to_create }} user home
  ansible.builtin.file:
    path: "{{ user_created.home }}"
    state: directory
    owner: "{{ user_created.name }}"
    group: "{{ user_created.group }}"
    mode: "0700"
  become: true

- name: Add {{ user_to_create }} user to the sudoers
  ansible.builtin.copy:
    dest: "/etc/sudoers.d/{{ user_to_create }}"
    content: "{{ user_to_create }} ALL=(ALL) NOPASSWD: ALL\n"
    # content: "{{ user_to_create }} ALL=(ALL) PASSWD: /sbin/ifconfig, /usr/bin/netstat"
    # content: "{{ user_to_create }} ALL=(ALL) PASSWD: /usr/bin/apt"
  become: true

- name: Deploy SSH key for {{ user_to_create }}
  ansible.posix.authorized_key:
    user: "{{ user_created.name }}"
    key: "{{ lookup('file', key_dir ~ '/' ~ key_public_name) }}"
    comment: "ansible@{{ inventory_hostname }}"
  become: true
