# - name: Gather fresh facts for this host
#   ansible.builtin.setup:
#     gather_subset: all

- name: Print Kernel
  ansible.builtin.debug:
    msg: "{{ ansible_facts['kernel'] }} {{ ansible_facts['kernel_version'] }}"

- name: Print OS
  ansible.builtin.debug:
    msg: "{{ ansible_os_family }} - {{ ansible_facts['distribution'] }} {{ ansible_facts['distribution_version'] }} ({{ ansible_facts['distribution_release'] }})"

- name: Print Arch
  ansible.builtin.debug:
    msg: "{{ ansible_facts['architecture'] }}"

- name: Print Hostname
  ansible.builtin.debug:
    msg: "{{ ansible_facts['hostname'] }}"

- name: Print FQDN
  ansible.builtin.debug:
    msg: "{{ ansible_facts['fqdn'] }}"

- name: Print Date
  ansible.builtin.debug:
    msg: "{{ ansible_facts['date_time']['date'] }} {{ ansible_facts['date_time']['time'] }} {{ ansible_facts['date_time']['tz'] }}"

- name: Print ansible user, home, shell
  ansible.builtin.debug:
    msg: "{{ ansible_facts['user_id'] }} {{ ansible_facts['user_dir'] }} {{ ansible_facts['user_shell'] }}"

- name: Print Package Manager
  ansible.builtin.debug:
    msg: "{{ ansible_facts['pkg_mgr'] }}"

- name: Print Python version
  ansible.builtin.debug:
    msg: "{{ ansible_facts['python_version'] }}"

- name: Print default IP
  ansible.builtin.debug:
    msg: "{{ ansible_facts.default_ipv4.address }}"
