- name: Filter users with key_dir and key_name defined
  ansible.builtin.set_fact:
    users_with_keys: >-
      {{
        ssh_users_to_create
        | selectattr('key_dir', 'defined')
        | selectattr('key_name', 'defined')
        | list
      }}

- name: Ensure directory exists for SSH keys
  ansible.builtin.file:
    path: "{{ item.key_dir }}"
    state: directory
    mode: '0700'
  loop: "{{ users_with_keys }}"
  loop_control:
    label: "{{ item.user }}"

- name: Generate SSH key if it does not exist
  community.crypto.openssh_keypair:
    path: "{{ item.key_dir }}/{{ item.key_name }}"
    type: "{{ item.key_type | default('rsa') }}"
    regenerate: 'partial_idempotence'
    state: present
    force: no
  loop: "{{ users_with_keys }}"
  loop_control:
    label: "{{ item.user }}"
