- name: restart_cachefilesd
  ansible.builtin.service:
    name: cachefilesd
    state: restarted
  become: true

- name: reload_systemd_deamon
  ansible.builtin.service:
    daemon_reload: true
